---
title: "Resources"
aliases:
  - resourses.html   # keeps old bookmarks/links working after the rename
---

## Good recommendations to start with

-   Genomics tools and resources - [GitHub](https://github.com/crazyhottommy/getting-started-with-genomics-tools-and-resources?tab=readme-ov-file)

-   [NCBI Tutorials and Webinars](https://www.ncbi.nlm.nih.gov/home/tutorials/)

-   [EMBL-EBI Training](https://www.ebi.ac.uk/training/online/)

-   [Linux Basics by Martin Hölzer, EEBG 2024](https://docs.google.com/presentation/d/14xELo7lDbd-FYuy144ZDK1tV_ZBdBYun_COelrKYWps/edit?slide=id.p#slide=id.p)

-   [Introduction to UNIX command line](https://ngs-docs.github.io/2021-august-remote-computing/introduction-to-the-unix-command-line.html)

-   [Workflow Management System by Martin Hölzer, EEBG 2024](https://docs.google.com/presentation/d/1CgFtt7W3c4mlJ9Asd0cQA0L72dPEiGHhonAhxWoDwZA/edit?slide=id.p1#slide=id.p1)

## Tools

-   [samtools](https://www.htslib.org/)
-   [bcftools](https://samtools.github.io/bcftools/)
-   [fastp](https://github.com/OpenGene/fastp)
-   [bwa](https://github.com/lh3/bwa)
-   [various vcf tools](https://knausb.github.io/vcfR_documentation/vcf_software.html)
-   [IGV - Integrative Genomics Viewer](https://igv.org/)
-   [SnpEff - genetic variant annotation and effect prediction tool](https://pcingola.github.io/SnpEff/)

## Sequencing principles

-   [Illumina Sequencing adapters](https://teichlab.github.io/scg_lib_structs/methods_html/Illumina.html)

## Bioinformatics courses & Trainings

-   [Introduction to computational biology by Mike Love](https://biodatascience.github.io/compbio/)
-   [Applied Computational Genomics by Aaron Quinlan](https://github.com/quinlan-lab/applied-computational-genomics#course-lecture-slides)
-   [Structural and Functional Genomics Course](https://drive.google.com/drive/folders/1SBncGk2tQ1PPmdaPAjz-NIovsROZKrKj)
-   [Speciation & Population Genomics: a how-to-guide](https://speciationgenomics.github.io/)
 - [Біоінформатика малих геномних варіантів (Youtube Genomics UA)](https://www.youtube.com/watch?v=2x5XLqU_U-A) 
- [Introduction to Bioconductor in R - DataCamp](https://www.datacamp.com/courses/introduction-to-bioconductor-in-r?utm_cid=22816457655&utm_aid=183907726959&utm_campaign=250722_1-ps-dscia~tech~r-p2_2-b2c_3-emea_4-prc_5-na_6-na_7-le_8-pdsh-go_9-nb-e_10-na_11-na&utm_loc=9198724-&utm_mtd=b-c&utm_kw=r%20bioinformatics%20course&utm_source=google&utm_medium=paid_search&utm_content=ps-dscia~emea-en~tech~r~bioinformatics&gad_source=1&gad_campaignid=22816457655&gclid=CjwKCAiAwqHIBhAEEiwAx9cTeaE6BHsmqDTmVyWdj5EPOzcTVk21rEpomgTrWCxqAvxNqhIeBSeuMhoC4DkQAvD_BwE)
## Books

-   [Генетика Сиволоб](https://biomed.knu.ua/images/stories/Kafedry/Genetika/Biblioteka/Genetyka_site/Genetics_sivolob_et_al.pdf)
-   [Молекулярна біологія Сиволоб 2023](https://drive.google.com/file/d/17B5vbVynpqq8co08fYty7iT3k0TSxMAv/view)
-   [Modern Statistics for Modern Biology](https://www.huber.embl.de/msmb/)

## Useful Links / Opportunities in Ukraine

-   [NGO Bioinformatics for Ukraine](https://bioinformaticsforukraine.com/)
-   [NGO GenomicsUA](https://genomics.org.ua/legal/)
-   [UBDS\^3 Summer School](https://www.bds3.org/)
-   [CRABS Summer School](https://crabs.kse.ua/)
-   [Ukrainian school in Evolutionary Biology](https://biology.karazin.ua/useb-evolbiol.html)
-   [Odesa Bio Summer School](https://www.facebook.com/BioSummerSchoolONU/)
